### ISSUE TITLE
santa_events table is marking every single process execution as an event

### ISSUE THREAD

**Issue by clong** [trailofbits/osquery-extensions#30] opened 2018-09-04 18:29 UTC
Hi folks,

I recently upgraded to osquery 3.3.0, Santa v0.9.28, and the new Trail of Bits extension and since then, I'm seeing basically every single process execution get added to the santa_events table:

```
osquery> select count(*) from santa_events;
+----------+
| count(*) |
+----------+
| 180796   |
+----------+

+--------------------------+------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------+---------+
| timestamp                | path                                                                                                                         | shasum                                                           | reason  |
+--------------------------+------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------+---------+
| 2018-09-04T18:14:51.168Z | /Applications/Google Chrome.app/Contents/Versions/68.0.3440.106/Google Chrome Helper.app/Contents/MacOS/Google Chrome Helper | 57480321cc69717dff5889374e493130825011d882f76e4d1db96912f1f10c96 | UNKNOWN |
| 2018-09-04T18:14:49.190Z | /bin/df                                                                                                                      | 87d14508b381903825986fc10a7bc91035a47ce6712b24c049fac001cfb750be | CERT    |
| 2018-09-04T18:14:48.296Z | /Applications/Google Chrome.app/Contents/Versions/68.0.3440.106/Google Chrome Helper.app/Contents/MacOS/Google Chrome Helper | 57480321cc69717dff5889374e493130825011d882f76e4d1db96912f1f10c96 | UNKNOWN |
| 2018-09-04T18:14:44.095Z | /System/Library/CoreServices/LocationMenu.app/Contents/MacOS/LocationMenu                                                    | c8887435ac16812dc00501b97ab1ebda4020fce6e0efe229cfee4b327c4b6c38 | CERT    |
| 2018-09-04T18:14:44.095Z | /usr/libexec/xpcproxy                                                                                                        | 0b8fbba98f048a3aa0fc20aa7d3777f5e9e06afa6b96cdba02fe8b5486af5479 | CERT    |
| 2018-09-04T18:14:42.883Z | /Applications/Google Chrome.app/Contents/Versions/68.0.3440.106/Google Chrome Helper.app/Contents/MacOS/Google Chrome Helper | 57480321cc69717dff5889374e493130825011d882f76e4d1db96912f1f10c96 | UNKNOWN |
| 2018-09-04T18:14:42.882Z | /Applications/Google Chrome.app/Contents/Versions/68.0.3440.106/Google Chrome Helper.app/Contents/MacOS/Google Chrome Helper | 57480321cc69717dff5889374e493130825011d882f76e4d1db96912f1f10c96 | UNKNOWN |
| 2018-09-04T18:14:30.319Z | /private/var/osquery/extensions/trailofbits_osquery_extensions.ext                                                           | 60e3a7a9e61008148823e0ebe36eaab6143a88d13e25d5b42e8fd7c28629106d | UNKNOWN |
| 2018-09-04T18:14:30.292Z | /usr/local/bin/osqueryd                                                                                                      | 10e78f5d173499e340c3582eeded49bbadde83f515e501d8a37a270d87138f56 | UNKNOWN |
+--------------------------+------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------+---------+
```
I'm guessing something with the way Santa logs or the extension classifies events has changed.

**Comment by mike-myers-tob** [comment] 2018-09-04 19:20
It is a regression introduced in a previous commit, we changed the extension to be able to read `ALLOW` events as well as `DENY`, but did not also add a column by which to filter to just `DENY` events. We can fix it by adding that column, and then querying would work like `select * from santa_events where action="DENY"`

Would that be sensible?

**Comment by clong** [comment] 2018-09-04 19:59
I think that's okay, but I'm not sure what the perf impact of spooling all the allow events (essentially all process execution events) into the santa_events table is. I think the solution you're proposing should work fine for us.

**Comment by clong** [comment] 2018-09-04 20:27
I'm good with that! I wasn't aware that it wasn't actually an events table, so that's good to know.

**Comment by mike-myers-tob** [comment] 2018-09-05 00:18
Do you know what kind of query execution time you see, with it returning `180796` rows? Because returning even a few thousand rows is near-instantaneous on this test system, but I know that Santa rolls over its logs into compressed logs, so we may see a performance hit from decompressing those to search them (which we do).

**Comment by clong** [comment] 2018-09-05 17:06
```
$ time echo 'select count(*) from santa_events;' | sudo osqueryi
+----------+
| count(*) |
+----------+
| 148523   |
+----------+

real	0m2.643s
user	0m2.377s
sys	0m0.481s
```

**Comment by mike-myers-tob** [comment] 2018-09-05 17:30
Ok, ~2.5 seconds is still a bit slow. I'll file a new issue to implement a performance speedup on the new `santa_allowed` table using the constraints feature that @alessandrogario suggested, and then the `santa_allowed` table can be queried faster using `WHERE` clauses. In the meantime, the code change is merged so that you can just check one kind of decision or the other.

**Comment by clong** [comment] 2018-09-17 20:40
Hey @mike-myers-tob - I'm still seeing quite a few non-blocked events in `santa_denied` - not exactly sure what's going on here:

```
Using a virtual database. Need help, type '.help'
osquery> select count(*) from santa_allowed;
+----------+
| count(*) |
+----------+
| 47667    |
+----------+
osquery> select count(*) from santa_denied;
+----------+
| count(*) |
+----------+
| 33524    |
+----------+
```

```
osquery> select * from santa_denied limit 5;
+--------------------------+-----------------------+------------------------------------------------------------------+--------+
| timestamp                | path                  | shasum                                                           | reason |
+--------------------------+-----------------------+------------------------------------------------------------------+--------+
| 2018-09-15T12:38:17.889Z | /usr/libexec/xpcproxy | 0b8fbba98f048a3aa0fc20aa7d3777f5e9e06afa6b96cdba02fe8b5486af5479 | CERT   |
| 2018-09-15T12:38:32.866Z | /usr/libexec/xpcproxy | 0b8fbba98f048a3aa0fc20aa7d3777f5e9e06afa6b96cdba02fe8b5486af5479 | CERT   |
| 2018-09-15T12:38:33.703Z | /usr/bin/profiles     | 557617eb2d8d9d0c66749be671280a760e33a3c78cfb4c6195953bbba5fdcf91 | CERT   |
| 2018-09-15T12:38:33.703Z | /usr/libexec/xpcproxy | 0b8fbba98f048a3aa0fc20aa7d3777f5e9e06afa6b96cdba02fe8b5486af5479 | CERT   |
| 2018-09-15T12:38:33.703Z | /usr/libexec/xpcproxy | 0b8fbba98f048a3aa0fc20aa7d3777f5e9e06afa6b96cdba02fe8b5486af5479 | CERT   |
+--------------------------+-----------------------+------------------------------------------------------------------+--------+
```

**Comment by mike-myers-tob** [comment] 2018-09-17 20:53
There must be a bug, I'll step through it tonight and look.

**Comment by mike-myers-tob** [comment] 2018-09-17 22:48
I can't reproduce the problem; is it possible to share the loglines in your `/var/db/santa/santa.log` that correspond to the `santa_denied` rows in your last comment? Ostensibly they would look like the following: 

```
[2018-09-17T22:24:59.472Z] I santad: action=EXEC|decision=ALLOW|reason=CERT|sha256=0b8fbba98f048a3aa0fc20aa7d3777f5e9e06afa6b96cdba02fe8b5486af5479|cert_sha256=2aa4b9973b7ba07add447ee4da8b5337c3ee2c3a991911e80e7282e8a751fc32|cert_cn=Software Signing|pid=48033|ppid=1|uid=0|user=root|gid=0|group=wheel|mode=M|path=/usr/libexec/xpcproxy
```

Maybe there is a caching issue with regard to osquery or RocksDB? @alessandrogario 

Here is how I tested:

1. Check the sha-256 sum on a binary:
```
$ shasum -a 256 /sbin/ping
3b02797073a33fcbbbeca4bb1502fba4402b77e54547c140577035c2961bc0d8  /sbin/ping
```

2. Using osquery, create a blacklisted-binary rule:
```
osquery> INSERT INTO santa_rules (shasum, state, type, custom_message) VALUES ("3b02797073a33fcbbbeca4bb1502fba4402b77e54547c140577035c2961bc0d8", "blacklist", "binary", "Disallow macOS 10.13.6 /sbin/ping.");
osquery> select * from santa_rules;
+------------------------------------------------------------------+-----------+-------------+------------------------------------+
| shasum                                                           | state     | type        | custom_message                     |
+------------------------------------------------------------------+-----------+-------------+------------------------------------+
| 33b9aee3b089c922952c9240a40a0daa271bebf192cf3f7d964722e8f2170e48 | whitelist | certificate |                                    |
| 3b02797073a33fcbbbeca4bb1502fba4402b77e54547c140577035c2961bc0d8 | blacklist | binary      | Disallow macOS 10.13.6 /sbin/ping. |
| 2aa4b9973b7ba07add447ee4da8b5337c3ee2c3a991911e80e7282e8a751fc32 | whitelist | certificate |                                    |
+------------------------------------------------------------------+-----------+-------------+------------------------------------+
```

3. Attempt to run the blacklisted binary, trigger a Santa denial:
```
ToB-Mac-VM:osquery trailofbits$ ping -?
-bash: /sbin/ping: Operation not permitted
ToB-Mac-VM:osquery trailofbits$ 
Santa

Disallow macOS 10.13.6 /sbin/ping.

Path:       /sbin/ping
Identifier: 3b02797073a33fcbbbeca4bb1502fba4402b77e54547c140577035c2961bc0d8
Parent:     bash (47964)
```

4. Using osquery again, check the logged `DENY` and `ALLOWED` decisions:
```
osquery> select * from santa_denied;
+--------------------------+-----------------------+------------------------------------------------------------------+--------+
| timestamp                | path                  | shasum                                                           | reason |
+--------------------------+-----------------------+------------------------------------------------------------------+--------+
| 2018-09-17T22:31:51.771Z | /sbin/ping            | 3b02797073a33fcbbbeca4bb1502fba4402b77e54547c140577035c2961bc0d8 | BINARY |
+--------------------------+-----------------------+------------------------------------------------------------------+--------+
osquery> select count(*) from santa_allowed;
+----------+
| count(*) |
+----------+
| 2501     |
+----------+
osquery> select count(*) from santa_denied;
+----------+
| count(*) |
+----------+
| 1        |
+----------+
```

**Comment by mike-myers-tob** [comment] 2018-10-01 02:56
Since the early issue you saw that seems to have been caching related, have you had any issues, @clong ? If not, am I good to close this?

**Comment by clong** [comment] 2018-10-01 03:02
I believe so. I won’t be able to test a wider rollout for a few weeks, so feel free to close this in the meantime!

**Closed** 2018-10-01 03:04 UTC
Labels: bug, santa
